# Golang 错误处理

* 错误只处理一次，不要把日志打的到处是
* 错误可以上报返回，由最上层去处理
* 返回错误前把堆栈和自定义信息打包进去，保留根因
* wrap在层层错误返回时其实是串在了一个链表上

### 少废话上代码

```go
package main

import (
	"fmt"

	"github.com/pkg/errors" // 注意在公共库当中，我们一般不使用这个
)

// 自定义业务错误
type errorBiz struct {
	s string
}

func (e *errorBiz) Error() string {
	return e.s
}

// 自定义数据错误
type errorDao struct {
	s string
}

func (e *errorDao) Error() string {
	return e.s
}

func main() {
	err := Biz()
	if err != nil {
		// 获取根因
		originErr := errors.Cause(err)
		fmt.Println(originErr)

		// 判断错误类型
		switch originErr.(type) {
		case *errorBiz:
			fmt.Println("业务错误")
		case *errorDao:
			fmt.Println("数据错误")
		default:
			// 未知错误
		}

		// 打印堆栈信息，由最上层处理错误，一个错误只处理一次
		fmt.Printf("%+v", err)
	}
}

// 业务
func Biz() error {
	err := Dao()
	if err != nil {
		// 不是自己造成的错误，向上透传错误，不打日志，不wrap
		return err
	}
	errBiz := &errorBiz{
		s: "this user has no permision",
	}
	// 自己造成的错误，wrap保存堆栈信息，向上返回
	return errors.Wrap(errBiz, "biz err")
}

// 数据
func Dao() error {
	// return nil
	err := &errorDao{
		s: "sql err",
	}
	// 保留根因
	return errors.Wrap(err, "dao err")
}
```

